services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5434:5432"
    env_file:
      - .env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8082:8080"

volumes:
  pgdata:
