name: Deploy to EC2

on:
  push:
    branches:
      - master
    paths:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: SSH & Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e  # stop on error

            cd ~

            # Clone repo if not already there
            if [ ! -d workout-app ]; then
              git clone https://github.com/Hammad8ahmad/workout-app.git
            else
              cd workout-app
              git pull origin master
            fi

            cd ~/workout-app

            # Clean up frontend to avoid bloating the server
            rm -rf frontend

            # Inject .env.prod from GitHub Secrets
            echo "${{ secrets.ENV_PROD_CONTENTS }}" > backend/.env.prod

            # Deploy backend
            cd backend
            docker system prune -f
            ./mvnw clean package -DskipTests
            docker-compose -f docker-compose.prod.yml down -v
            docker-compose -f docker-compose.prod.yml up -d --build
          EOF
