name: Deploy to EC2

on:
  push:
    branches:
      - master
    paths:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: SSH & Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Clone repo if not present
            if [ ! -d ~/workout-app ]; then
              git clone https://github.com/Hammad8ahmad/workout-app.git
            fi

            cd ~/workout-app
            git pull origin master

            # Remove frontend to avoid bloating
            rm -rf frontend

            # Create .env.prod with secret contents
            echo "${{ secrets.ENV_PROD_CONTENTS }}" > backend/.env.prod

            # Deploy backend
            cd backend
            docker-compose down
            docker-compose up -d --build
          EOF
